### ISSUE TITLE
Can`t register!

### ISSUE THREAD

**Issue by chenpaner** [kamiya-seisaku/blender-shortcut-organizer#1]
Traceback (most recent call last):
  File "G:\Blender Program\stable\blender-3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "G:\Blender Program\stable\blender-3.6\3.6\scripts\addons\blender-shortcut-organizer-main\__init__.py", line 124, in register
    getattr(bpy.types, menu_type, None).append(add_context_menu) if getattr(bpy.types, menu_type, None) is not None else None
AttributeError: type object 'PME_OT_context_menu' has no attribute 'append'

When I registered the plug-in in a completely new blender without any settings, there was no problem, but when I set the shortcut keys, it didn't work, and when I pressed OK, blender crashed!

**Comment by kamiya-seisaku** [comment]
This is work in progress and very unstable so far, sorry to bother you.  I will update the readme accordingly.
